# Generated by Django 5.1.1 on 2025-09-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=2, verbose_name='部門')),
                ('item_name', models.CharField(max_length=12, verbose_name='社内品名')),
                ('process_code', models.CharField(max_length=6, verbose_name='工程ｺｰﾄﾞ')),
                ('process_name', models.CharField(max_length=20, verbose_name='工程名')),
                ('total_qty', models.PositiveIntegerField(verbose_name='処理数')),
                ('good_qty', models.PositiveIntegerField(verbose_name='良品数')),
                ('board_total_qty', models.PositiveIntegerField(verbose_name='基板数')),
                ('board_good_qty', models.PositiveIntegerField(verbose_name='基板良品数')),
                ('created_at', models.CharField(max_length=16, verbose_name='作業日時')),
            ],
        ),
    ]
