# Generated by Django 5.1.1 on 2025-09-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprocess',
            name='created_at',
            field=models.CharField(max_length=20, verbose_name='作業日時'),
        ),
    ]
